freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-rc3-amd64
  script:
    - pkg update
    - pkg install -y git python27 py27-pip
    - git clone https://github.com/YutaroHayakawa/generic-ebpf
    - cd generic-ebpf
    - pip install -r requirements.txt
    - make
    - make check

freebsd_kernel_task:
  freebsd_instance:
    image: freebsd-12-0-rc3-amd64
  script:
    - pkg update
    - pkg install -y git python27 py27-pip
    - git clone https://github.com/YutaroHayakawa/generic-ebpf
    - cd generic-ebpf
    - pip install -r requirements.txt
    - make
    - make load
    - make check-kern

linux_task:
  container:
    image: ubuntu:latest
  script:
    - apt update
    - apt -y install python-pip git libelf-dev build-essential libc6-dev-i386
    - git clone https://github.com/YutaroHayakawa/generic-ebpf
    - cd generic-ebpf
    - pip install -r requirements.txt
    - make
    - make check

# linux_kernel_task:
#   container:
#     image: ubuntu:latest
#   script:
#     - apt update
#     - apt -y install python-pip git libelf-dev build-essential libc6-dev-i386 module-init-tools linux-headers-`uname -r`
#     - git clone https://github.com/YutaroHayakawa/generic-ebpf
#     - cd generic-ebpf
#     - pip install -r requirements.txt
#     - make
#     - make load
#     - make check
