os: linux
language: cpp
compiler:
  - gcc
  - g++
python:
  - "2.7"
install:
  - ./install_deps.sh
  - pip install --user cpp-coveralls
script:
  - platform=Linux make user COVERAGE=1
  - platform=Linux make tests
  - platform=Linux make do_test
after_success:
  - coveralls --gcov-options '\-lp' -r $PWD/sys/dev/ebpf
