language: cpp
compiler:
  - gcc
  - g++
python:
  - "2.7"
matrix:
  include:
    - os: linux
      env: platform=Linux
    - os: osx
      env: platform=Darwin
install:
  - ./install_deps.sh
  - pip install --user cpp-coveralls
script:
  - COVERAGE=1 make
  - make tests
  - make do_test
after_success:
  - coveralls --gcov-options '\-lp' -r $PWD/sys/dev/ebpf -E ".*\.h"
