os:
  - linux
language: cpp
compiler:
  - gcc
  - g++
python:
  - "2.7"
install:
  - pip install --user -r requirements.txt
  - pip install --user cpp-coveralls
script:
  - COVERAGE=1 make tests
  - make check
after_success:
  - coveralls --exclude tests --exclude extern --exclude sys/dev/ebpf/tommyds/ --gcov-options '\-lp'
