os: linux
language: cpp
compiler:
  - gcc
  - g++
python:
  - "2.7"
install:
  - ./install_deps.sh
  - pip install --user cpp-coveralls
script:
  - ./configure
  - COVERAGE=1 make ebpf_user
  - make tests
  - make do_test
after_success:
  - coveralls --gcov-options '\-lp' -r $PWD/sys/dev/ebpf -E ".*\.h"
