os: linux
language: cpp
compiler:
  - gcc
  - g++
python:
  - "2.7"
install:
  - git submodule init && git submodule update
  - pip install --user -r requirements.txt
  - pip install --user cpp-coveralls
script:
  - ./configure
  - COVERAGE=1 make ebpf_user
  - make tests
  - make do_test
after_success:
  - coveralls --gcov-options '\-lp' -r $PWD/sys/dev/ebpf -E ".*\.h" -e "tommyds"
