os:
  - linux
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libelf-dev build-essential libc6-dev-i386
install:
  - pip install --user -r requirements.txt
  - pip install --user cpp-coveralls
script:
  - CFLAGS="-std=gnu99" UNAME_s="Linux" COVERAGE=1 make
  - UNAME_s="Linux" make check
after_success:
  - coveralls --exclude tests --exclude extern --exclude contrib --exclude benchmark --exclude FreeBSD --gcov-options '\-lp'
